<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>False</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Resources\**" />
    <Compile Remove="View\**" />
    <EmbeddedResource Remove="Resources\**" />
    <EmbeddedResource Remove="View\**" />
    <None Remove="Resources\**" />
    <None Remove="View\**" />
    <Page Remove="Resources\**" />
    <Page Remove="View\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Fonts\SF-Pro.ttf" />
    <None Remove="Images\rating.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\SF-Pro.ttf" />
    <Resource Include="Images\rating.ico" />      
  </ItemGroup>

</Project>
